server:
  port: 8080

spring:
  rabbitmq:
    #    主机
    host: localhost
    #    端口
    port: 5672
    #    虚拟主机
    virtual-host: /
    #    用户名
    username: lqs
    #    密码
    password: lqs

    listener:
      simple:
        prefetch: 1 # 配置每次预取1条消息，默认是所有