# 配置日志等级
logging:
  # 设置分组对某个组设置日志级别
  group:
    log1: com.lqs.controll, com.lqs
    log2: com.fasterxml

  level:
    root: info
    # 给指定包设置等级
    com.lqs.controll: debug
    # 设置分组级别
    log1: debug

  # 日志记录
  file:
    path: logs

  logback:
    rollingpolicy:
      max-file-size: 30KB
      file-name-pattern: log.%d{yyyy-MM-dd}.%i.log


# 热部署
# 排除和关闭
spring:
  devtools:
    restart:
      exclude: static/**, templates/**
      # 关闭，不太好，可能级别更高的配置文件将这个覆盖，最好在启动文件哪里关闭
#      enabled: false


