# 多环境配置

# 应用配置
# 主配置
# 加载的时候，先加载group，然后加载active， 后加载的可以覆盖先加载的
spring:
  profiles:
    active: test # 选择开发环境的配置
    group:
      "dev": devDB,devMVC
      "pro": proDB,proMVC
      "test": testDB,testMVC
#---
#
## 设置多环境
## 选配一
#server:
#  port: 1219 # 配置的测试环境的端口
#spring:
#  config:
#    activate:
#      on-profile: test
#
#---
## 选配二
#server:
#  port: 1218 # 配置的开发环境的端口
#spring:
#  config:
#    activate:
#      on-profile: dev
